### ISSUE TITLE
Node 10 doesn't export GC information

### ISSUE THREAD

**Issue by jonnyarnold** [trussle/tricorder#34]
[Builds on Node 10 are failing](https://travis-ci.org/trussle/tricorder/jobs/397958723):

```
  ● index › metrics › third party metrics › Given metrics running, should include gc metrics

    expect(string).toContain(value)

    Expected string:
      "<redacted from this snippet>"
    To contain value:
      "nodejs_gc_runs_total"
```

It looks like Node 10's internals have been altered not to show this information.

**Comment by timReynolds** [comment]
I've already looked into this and created an issue in the upstream repository. https://github.com/SimenB/node-prometheus-gc-stats

**Comment by jonnyarnold** [comment]
Cool, just linking that up: https://github.com/SimenB/node-prometheus-gc-stats/pull/39

**Comment by timReynolds** [comment]
This has been resolved with the merge of [43](https://github.com/trussle/tricorder/pull/43)
